[package]
name = "frosty_vm"
version = "0.1.0"
authors = ["tyukiand <tyukiand@protonmail.ch>"]
edition = "2018"

[dependencies]
uuid = { version = "0.7.2", features = ["v4"] }
clap = "2.32.0"
trim-margin = "0.1.0"
